version: "3.9"

services:
  web-app-prod:
    container_name: web-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

  mock-api:
    container_name: mock-api
    image: jsonserver:latest
    build:
      context: ./mock-api
      dockerfile: Dockerfile.mock-api
    ports:
      - "3100:3100"
    volumes:
      - ./mock-api/db.json:/data/db.json 
    # environment:
    #   - MOCK_API_ENV=development
