version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "always"
    container_name: "web-app"
    ports:
      - "3000:3000"
    volumes:
      - ./:/web-app
      - /web-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: sh -c 'yarn run dev --host=0.0.0.0'
  
  mock-api:
    build:
      context: ./mock-api 
      dockerfile: Dockerfile
    restart: "always"
    container_name: "mock-api"
    ports:
      - "3100:3100"
    volumes:
      - ./mock-api:/mock-api
    command: ["npm", "start"]
